import { apiFetch } from "./api.js";
import { appState } from "./state.js";

/* =========================================
INIT
========================================= */
document.addEventListener("DOMContentLoaded", async () => {
  resetItineraryUI();
});

/* =========================================
EVENTOS DE CONTEXTO
========================================= */
document.addEventListener("travel-selected", async () => {
  await loadItineraryByTravel();
});

document.addEventListener("travel-cleared", () => {
  resetItineraryUI();
});

document.addEventListener("client-selected", () => {
  if (!appState.activeTravelId) {
    resetItineraryUI();
  }
});

/* =========================================
GUARDAR ITINERARIO
========================================= */
document.addEventListener("click", async e => {
  if (!e.target.closest("[data-itinerary-save]")) return;

  if (!appState.activeTravelId) {
    alert("Seleccioná un viaje primero");
    return;
  }

  try {
    const payload = {
      viaje_id: Number(appState.activeTravelId),
      version: getItineraryField("version"),
      issue_date: getItineraryField("issueDate") || null,
      notes: getItineraryField("notes") || null,
      auto_generated: isAutoGeneratedChecked(),
      pdf_name: getSelectedPdfName(),
      pdf_path: null
    };

    const existingId = getItineraryRecordId();

    let saved;

    if (existingId) {
      const res = await apiFetch(`/itinerarios/${existingId}`, {
        method: "PUT",
        body: JSON.stringify(payload)
      });
      saved = await safeJson(res);
    } else {
      const res = await apiFetch("/itinerarios", {
        method: "POST",
        body: JSON.stringify(payload)
      });
      saved = await safeJson(res);
    }

    hydrateItineraryForm(saved);
    renderItineraryPreview(saved);
    alert("Itinerario guardado");
  } catch (err) {
    console.error("SAVE ITINERARY ERROR:", err);
    alert("Error guardando itinerario");
  }
});

/* =========================================
CARGAR POR VIAJE
========================================= */
async function loadItineraryByTravel() {
  if (!appState.activeTravelId) {
    resetItineraryUI();
    return;
  }

  try {
    const res = await apiFetch(`/itinerarios/viaje/${appState.activeTravelId}`, {
      method: "GET"
    });

    const itinerary = await safeJson(res);

    if (!itinerary) {
      resetItineraryUI();
      return;
    }

    hydrateItineraryForm(itinerary);
    renderItineraryPreview(itinerary);
  } catch (err) {
    console.error("LOAD ITINERARY ERROR:", err);
    resetItineraryUI();
  }
}

/* =========================================
FORM HELPERS
========================================= */
function hydrateItineraryForm(data = {}) {
  setItineraryRecordId(data.id || "");
  setItineraryField("version", data.version || "");
  setItineraryField("issueDate", formatDateInput(data.issue_date));
  setItineraryField("notes", data.notes || "");

  const auto = document.querySelector('[data-itinerary="auto"]');
  if (auto) {
    auto.checked = Boolean(Number(data.auto_generated || 0));
  }

  clearPdfInputUI();

  if (data.pdf_name) {
    setPdfSelectedLabel(data.pdf_name);
  }
}

function resetItineraryUI() {
  setItineraryRecordId("");
  setItineraryField("version", "");
  setItineraryField("issueDate", "");
  setItineraryField("notes", "");

  const auto = document.querySelector('[data-itinerary="auto"]');
  if (auto) auto.checked = false;

  clearPdfInputUI();
  clearItineraryPreview();
}

function getItineraryField(key) {
  const el = document.querySelector(`[data-itinerary="${key}"]`);
  if (!el) return "";
  return el.value || "";
}

function setItineraryField(key, value) {
  const el = document.querySelector(`[data-itinerary="${key}"]`);
  if (el) {
    el.value = value ?? "";
  }
}

function isAutoGeneratedChecked() {
  return !!document.querySelector('[data-itinerary="auto"]')?.checked;
}

/* =========================================
PREVIEW
========================================= */
function renderItineraryPreview(data = {}) {
  const box = ensureItineraryPreviewBox();
  if (!box) return;

  if (!data || (!data.id && !data.version && !data.issue_date && !data.notes && !data.pdf_name)) {
    box.innerHTML = `
      <div class="small text-muted">
        No hay itinerario guardado para este viaje.
      </div>
    `;
    return;
  }

  box.innerHTML = `
    <div class="border rounded p-3 bg-light mt-3">
      <div class="d-flex justify-content-between align-items-start gap-3 flex-wrap">
        <div class="flex-grow-1">
          <div class="fw-semibold mb-2">Preview del itinerario</div>

          <div class="small mb-1">
            <strong>Versión:</strong> ${escapeHtml(data.version || "-")}
          </div>

          <div class="small mb-1">
            <strong>Fecha de emisión:</strong> ${escapeHtml(formatDateEs(data.issue_date) || "-")}
          </div>

          <div class="small mb-1">
            <strong>Generado automáticamente:</strong> ${Number(data.auto_generated || 0) ? "Sí" : "No"}
          </div>

          <div class="small mb-1">
            <strong>PDF asociado:</strong> ${escapeHtml(data.pdf_name || "Sin PDF")}
          </div>

          <div class="small mb-1">
            <strong>Observaciones:</strong> ${escapeHtml(data.notes || "-")}
          </div>
        </div>
      </div>
    </div>
  `;
}

function ensureItineraryPreviewBox() {
  let box = document.querySelector("[data-itinerary-preview]");
  if (box) return box;

  const section = document.querySelector('[data-section="itinerario"]');
  if (!section) return null;

  box = document.createElement("div");
  box.setAttribute("data-itinerary-preview", "");
  section.appendChild(box);

  return box;
}

function clearItineraryPreview() {
  const box = document.querySelector("[data-itinerary-preview]");
  if (box) {
    box.innerHTML = `
      <div class="small text-muted mt-3">
        No hay itinerario guardado para este viaje.
      </div>
    `;
  }
}

/* =========================================
PDF INPUT AUX
========================================= */
function getSelectedPdfName() {
  const input = document.querySelector('[data-itinerary="pdf"]');
  if (!input?.files?.length) {
    return document.querySelector("[data-itinerary-pdf-label]")?.textContent || null;
  }

  return input.files[0]?.name || null;
}

function clearPdfInputUI() {
  const input = document.querySelector('[data-itinerary="pdf"]');
  if (input) input.value = "";

  const label = document.querySelector("[data-itinerary-pdf-label]");
  if (label) label.textContent = "";
}

function setPdfSelectedLabel(name) {
  let label = document.querySelector("[data-itinerary-pdf-label]");
  if (!label) {
    const input = document.querySelector('[data-itinerary="pdf"]');
    if (!input?.parentElement) return;

    label = document.createElement("div");
    label.className = "small text-muted mt-1";
    label.setAttribute("data-itinerary-pdf-label", "");
    input.parentElement.appendChild(label);
  }

  label.textContent = name || "";
}

/* =========================================
ID OCULTO RUNTIME
========================================= */
function getItineraryRecordId() {
  return document.querySelector("[data-itinerary-record-id]")?.value || "";
}

function setItineraryRecordId(value) {
  let hidden = document.querySelector("[data-itinerary-record-id]");

  if (!hidden) {
    const section = document.querySelector('[data-section="itinerario"]');
    if (!section) return;

    hidden = document.createElement("input");
    hidden.type = "hidden";
    hidden.setAttribute("data-itinerary-record-id", "");
    section.appendChild(hidden);
  }

  hidden.value = value || "";
}

/* =========================================
UTILS
========================================= */
async function safeJson(res) {
  const contentType = res.headers.get("content-type") || "";
  if (!contentType.includes("application/json")) {
    return null;
  }
  return res.json();
}

function formatDateInput(value) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10); // para input
}

function formatDateEs(value) {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleDateString("es-AR");
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}